server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: admin
    # Issue 4: Hardcoded password in config file
    password: my-secret-password-123 
    
# Issue 5: Hardcoded API Token
stripe:
  api:
    token: sk_test_4eC39HqLyjWDarjtT1zdp7dc
